import Head from "next/head";
import { MainLayout } from "@/components/layout";
import { type NextPageWithLayout } from "@/pages/_app";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Profile: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

Profile.auth = true;

Profile.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "profile"])),
    },
  };
}

export default Profile;
